version: "3.5"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: area
    volumes:
      - db-data:/var/lib/data/postgres
      - ./db-dump:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "5432:5432"

  back:
    restart: unless-stopped
    build:
      context: ./back
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "8080:8080"
    env_file:
      - .back.env
    depends_on:
      - db
    volumes:
      - ./back/trelloRoute.js:/app/trelloRoute.js
      - ./back/routes:/app/routes
      - ./back/socket:/app/socket
      - ./back/tools:/app/tools
      - ./back/bot_discord:/app/bot_discord
      - ./back/bot_telegram:/app/bot_telegram
      - ./back/twitch:/app/twitch

  front:
    restart: unless-stopped
    build:
      context: ./front
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "8081:8081"
    env_file:
      - .front.env
    depends_on:
      - back
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public

volumes:
  db-data: