version: "3.5"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: area
    volumes:
      - db-data:/var/lib/data/postgres
      - ./db-dump:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"

  bot:
    restart: unless-stopped
    build:
      context: ./bot-discord
      target: prod
    depends_on:
      - db
    volumes:
      - ./bot-discord/server.js:/app/server.js

  back:
    restart: unless-stopped
    build:
      context: ./back
      target: prod
    ports:
      - "8080:8080"
    env_file:
      - .back.env
    depends_on:
      - db

  front:
    restart: unless-stopped
    build:
      context: ./front
      target: prod
    ports:
      - "8082:8082"
    env_file:
      - .front.env
    depends_on:
      - back
    volumes:
      - client:/apk

  mobile:
    build:
      context: ./mobile
      target: prod
    volumes:
      - apk:/usr/src/app/android/app/build/outputs/apk/:rw

volumes:
  db-data:
  apk: