version: "3.5"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: area
    volumes:
      - db-data:/var/lib/data/postgres
      - ./db-dump:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"

  back:
    restart: unless-stopped
    build:
      context: ./back
      target: prod
    ports:
      - "8080:8080"
    env_file:
      - .back.env
    depends_on:
      - db

  front:
    restart: unless-stopped
    build:
      context: ./front
      target: prod
    ports:
      - "8081:8081"
    env_file:
      - .front.env
    depends_on:
      - back
    volumes:
      - apk:/common_volume/apk

  mobile:
      build:
        context: ./mobile
        target: prod
      volumes:
        - apk:/common_volume/apk

volumes:
  db-data:
  apk: